staging-settings:
  user-workflow:
    workflow-name: tare-confidential-policy
    deployment-registry: private
  workflow-artifacts:
    workflow-path: ./src/main.ts
    config-path: ./config.example.json
    secrets-path: ./secrets.yaml
